# Generated by Django 2.2 on 2021-03-27 14:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('playlist_name', models.CharField(max_length=25, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('singer_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song_title', models.CharField(db_index=True, max_length=50)),
                ('album', models.CharField(db_index=True, max_length=50)),
                ('play_time', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('usergroup', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='VBIMusicApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='SongSingerMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('singer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singers', to='VBIMusicApp.Singer')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='VBIMusicApp.Song')),
            ],
            options={
                'unique_together': {('song_id', 'singer_id')},
            },
        ),
        migrations.CreateModel(
            name='SongPlayListMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VBIMusicApp.Playlist')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VBIMusicApp.Song')),
            ],
            options={
                'unique_together': {('playlist_id', 'song_id')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='singers',
            field=models.ManyToManyField(through='VBIMusicApp.SongSingerMapping', to='VBIMusicApp.Singer'),
        ),
        migrations.AddField(
            model_name='song',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VBIMusicApp.User'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(through='VBIMusicApp.SongPlayListMapping', to='VBIMusicApp.Song'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VBIMusicApp.User'),
        ),
    ]
