# Generated by Django 2.2 on 2021-03-29 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VBIMusicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 22, 28, 29, 112976)),
        ),
    ]
